export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',

  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',
}

export const categoryConstants = {
  GET_ALL_CATEGORY_REQUEST: 'GET_ALL_CATEGORY_REQUEST',
  GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
  GET_ALL_CATEGORY_FAILURE: 'GET_ALL_CATEGORY_FAILURE'
}

export const cartConstants = {
  CART_ITEM_REQUEST: 'CART_ITEM_REQUEST',
  CART_ITEM_SUCCESS: 'CART_ITEM_SUCCESS',
  CART_ITEM_FAILURE: 'CART_ITEM_FAILURE',

  ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
  ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
  ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',

  RESET_CART_SUCCESS: 'RESET_CART_SUCCESS'
}

export const productConstants = {
  GET_ALL_PRODUCT_REQUEST: 'GET_ALL_PRODUCT_REQUEST',
  GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
  GET_ALL_PRODUCT_FAILURE: 'GET_ALL_PRODUCT_FAILURE',

  // PRODUCT_FILTER_REQUEST: 'PRODUCT_FILTER_REQUEST',
  // PRODUCT_FILTER_SUCCESS: 'PRODUCT_FILTER_SUCCESS',
  // PRODUCT_FILTER_FAILURE: 'PRODUCT_FILTER_FAILURE',

  GET_PRODUCT_BY_SLUG: 'GET_PRODUCT_BY_SLUG',

  GET_PRODUCT_DETAIL_BY_ID_REQUEST: 'GET_PRODUCT_DETAIL_BY_ID_REQUEST',
  GET_PRODUCT_DETAIL_BY_ID_SUCCESS: 'GET_PRODUCT_DETAIL_BY_ID_SUCCESS',
  GET_PRODUCT_DETAIL_BY_ID_FAILURE: 'GET_PRODUCT_DETAIL_BY_ID_FAILURE'
}

export const addressConstants = {
  GET_USER_ADDRESS_REQUEST: 'GET_USER_ADDRESS_REQUEST',
  GET_USER_ADDRESS_SUCCESS: 'GET_USER_ADDRESS_SUCCESS',
  GET_USER_ADDRESS_FAILURE: 'GET_USER_ADDRESS_FAILURE',

  ADD_USER_ADDRESS_REQUEST: 'ADD_USER_ADDRESS_REQUEST',
  ADD_USER_ADDRESS_SUCCESS: 'ADD_USER_ADDRESS_SUCCESS',
  ADD_USER_ADDRESS_FAILURE: 'ADD_USER_ADDRESS_FAILURE',
}

export const orderConstants = {
  GET_USER_ORDER_REQUEST: 'GET_USER_ORDER_REQUEST',
  GET_USER_ORDER_SUCCESS: 'GET_USER_ORDER_SUCCESS',
  GET_USER_ORDER_FAILURE: 'GET_USER_ORDER_FAILURE',

  ADD_USER_ORDER_REQUEST: 'ADD_USER_ORDER_REQUEST',
  ADD_USER_ORDER_SUCCESS: 'ADD_USER_ORDER_SUCCESS',
  ADD_USER_ORDER_FAILURE: 'ADD_USER_ORDER_FAILURE',
}
